version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: python:3
    container_name: application
    restart: always
    entrypoint: ["python3", "./Air_Quality/manage.py", "runserver"]

volumes:
  db:
    driver: local