version: "3.3"

services:
  air-quality-db:
    image: "postgres:17-alpine"
    container_name: air-quality-db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - "pgdata_volume:/var/lib/postgresql/data"

volumes:
  pgdata_volume: {}
