# ansible-playbook -i inventory.yml playbook.yml
---
- name: Setup Project
  hosts: all
  become: true
  vars:
    ansible_user: "azureuser"

  tasks:

    - name: upgrade apt
      shell: apt upgrade -y
      shell: apt update -y
      become: yes

    # - name: add apt repo for python 10
    #   shell:
    #     apt install software-properties-common -y && add-apt-repository ppa:deadsnakes/ppa -y && apt update -y
    #   become: yes

    # - name: download python
    #   shell:
    #     apt install python3.8 -y
    #   become: yes

    - name: Install pip for Python 3
      apt:
        name: python3-pip
        state: present
      become: yes

    # - name: upgrade pip
    #   shell:
    #     pip3 install --upgrade pip

    - name: remove old repo
      shell:
          rm -rf /home/{{ ansible_user }}/PIS-proj
      ignore_errors: yes
      become: yes

    - name: clone repo
      git:
        repo: https://github.com/dominika232323/PIS_Air_Quality.git
        dest: /home/{{ ansible_user }}/PIS-proj
        update: yes

    - name: install python3 virtualenv
      apt:
        name: python3.12-venv
      become: yes

    - name: initialize virtualenv
      shell:
        python3 -m venv ./venv

    - name: activate vitualenv
      shell:
        . ./venv/bin/activate

    # - name: install python-setuptools
    #   package:
    #     name: python-setuptools
    #     state: present

    - name: install dependencies
      # pip:
      #   requirements: /home/{{ ansible_user }}/PIS-proj/requirements.txt
      #   executable: pip3
      # become: yes
      shell:
        ./venv/bin/pip3 install -r /home/{{ ansible_user }}/PIS-proj/requirements.txt

    - name: run app
      make:
        chdir: /home/{{ ansible_user }}/PIS-proj/
        target: up
